# Generated by Django 2.0 on 2017-12-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('subhead', models.TextField()),
                ('category', models.CharField(max_length=128)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=128)),
            ],
        ),
    ]
